### ISSUE TITLE
a directory cant be opened by using "cd [DirectoryName]" if its an empty container

### ISSUE THREAD

**Issue by parv0888** [richorama/AzureBlobDrive#7]
every empty container though can be opened in windows explorer which rightfully shows it empty 
but when using cd [DirectoryName] from command prompt it displays an error saying that "the specified directory does not exists". 
these is sm problem with the GetFoldersStartingWithFunction returning 0 length of ChildPath as 0. when it should not

**Comment by richorama** [comment]
Hi path,

I'll get back to you shortly, I'm away from my desk for a few days.

Richard.
From: parv0888
Sent: 09/12/2011 09:09
To: Richard Astbury
Subject: [AzureBlobDrive] a directory cant be opened by using "cd
[DirectoryName]" if its an empty container (#7)
every empty container though can be opened in windows explorer which
rightfully shows it empty
but when using cd [DirectoryName] from command prompt it displays an
error saying that "the specified directory does not exists".
these is sm problem with the GetFoldersStartingWithFunction returning
0 length of ChildPath as 0. when it should not

---

Reply to this email directly or view it on GitHub:
https://github.com/richorama/AzureBlobDrive/issues/7

**Comment by parv0888** [comment]
no probs.. as it is i figured out whats the prob and i hav sorted it out for the cd command.... 
i will edit the code for the other command that can be used and will giv u a pull request

**Comment by richorama** [comment]
Great, thanks
